# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='\u5206\u7c7b\u540d')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('mtime', models.DateTimeField(auto_now_add=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='\u8bc4\u8bba\u8be6\u60c5')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('mtime', models.DateTimeField(auto_now_add=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('mtime', models.DateTimeField(auto_now_add=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=200, unique=True, verbose_name='\u5e10\u53f7')),
                ('password', models.CharField(max_length=200, verbose_name='\u5bc6\u7801')),
                ('nickname', models.CharField(blank=True, max_length=200, verbose_name='\u6635\u79f0')),
                ('realname', models.CharField(blank=True, max_length=200, verbose_name='\u771f\u5b9e\u59d3\u540d')),
                ('gender', models.IntegerField(blank=True, null=True, verbose_name='\u6027\u522b')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('birthtime', models.TimeField(blank=True, null=True, verbose_name='\u51fa\u751f\u65f6\u95f4')),
                ('introduction', models.CharField(blank=True, max_length=1000, verbose_name='\u4e2a\u4eba\u4ecb\u7ecd')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001')),
                ('ctime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('mtime', models.DateTimeField(auto_now_add=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
        migrations.AddField(
            model_name='joke',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createjokes', to='joke.User', verbose_name='\u4f5c\u8005'),
        ),
        migrations.AddField(
            model_name='joke',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jokes', to='joke.Category', verbose_name='\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='joke',
            name='collects',
            field=models.ManyToManyField(blank=True, related_name='collectjokes', to='joke.User', verbose_name='\u6536\u85cf\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='joke',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likejokes', to='joke.User', verbose_name='\u70b9\u8d5e\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='comment',
            name='joke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='joke.Joke', verbose_name='\u88ab\u8bc4\u8bba\u7b11\u8bdd'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='joke.User', verbose_name='\u8bc4\u8bba\u4eba'),
        ),
    ]
