# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('mtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('mtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('mtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('realname', models.CharField(blank=True, max_length=200)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('birthtime', models.TimeField(blank=True, null=True)),
                ('introduction', models.CharField(blank=True, max_length=1000)),
                ('status', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('mtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='joke',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createjokes', to='joke.User'),
        ),
        migrations.AddField(
            model_name='joke',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jokes', to='joke.Category'),
        ),
        migrations.AddField(
            model_name='joke',
            name='collects',
            field=models.ManyToManyField(null=True, related_name='collectjokes', to='joke.User'),
        ),
        migrations.AddField(
            model_name='joke',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likejokes', to='joke.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='joke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='joke.Joke'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='joke.User'),
        ),
    ]
